---
language: ruby

matrix:
  include:
  - os: linux
    rvm: 2.1
  - os: osx
    rvm: 2.1
  - os: linux
    rvm: 2.2.6
  - os: osx
    rvm: 2.2.6
  - os: linux
    rvm: 2.3.1
  - os: osx
    rvm: 2.3.1
  fast_finish: true

script:
  - bundle install
  - make
  - bundle exec rake test
