---
language: ruby

matrix:
  include:
  - os: linux
    rvm: 2.1
  - os: osx
    rvm: 2.1
  - os: linux
    rvm: 2.2.7
  - os: osx
    rvm: 2.2.7
  - os: linux
    rvm: 2.3.4
  - os: osx
    rvm: 2.3.4
  - os: linux
    rvm: 2.4.0
  - os: osx
    rvm: 2.4.0
  - os: linux
    rvm: 2.5.0
  - os: osx
    rvm: 2.5.0
  fast_finish: true

script:
  - bundle install
  - make
  - bundle exec rake test
  - bundle exec rake examples
