---
language: ruby

matrix:
  include:
#  - os: linux
#    rvm: 2.2.10
#  - os: osx
#    rvm: 2.2.10
  - os: linux
    rvm: 2.3.8
  - os: osx
    rvm: 2.3.8
  - os: linux
    rvm: 2.4.6
  - os: osx
    rvm: 2.4.6
  - os: linux
    rvm: 2.5.5
  - os: osx
    rvm: 2.5.5
  - os: linux
    rvm: 2.6.3
  - os: osx
    rvm: 2.6.3
    osx_image: xcode10.2
    before_script:
      - ls -lah /Applications
      - sudo xcode-select -s /Applications/Xcode-10.2.1.app/Contents/Developer
      - clang --version
  fast_finish: true

before_install:
  - gem uninstall bundler --all
  - gem install bundler -v 1.17.2

script:
  - bundle install
  - make
  - bundle exec rake test
  - bundle exec rake examples
