cache:
- x86_64-4.9.2-release-win32-seh-rt_v4-rev4.7z
- i686-4.9.2-release-win32-dwarf-rt_v4-rev4.7z

install:
  - SET PATH=C:\Ruby%ruby_version%\bin;%PATH%
  - SET RAKEOPT=-rdevkit
  - C:\msys64\usr\bin\bash --login -c "pacman -Sy --noconfirm pacman"
  - C:\msys64\usr\bin\bash --login -c "pacman -S --needed --noconfirm mingw-w64-x86_64-toolchain autoconf automake libtool make patch mingw-w64-x86_64-libtool"
  - C:\msys64\usr\bin\bash --login -c "pacman -S --needed --noconfirm mingw-w64-zlib"

  - gcc --version
  - make --version
  - gem --version
  - bundle install

  - make

build: off

test_script:
  - bundle exec rake test
  - gem build fast_excel.gemspec

environment:
  matrix:
    - ruby_version: "24"
    - ruby_version: "24-x64"
#    - ruby_version: "23"
#    - ruby_version: "23-x64"
#    - ruby_version: "22"
#    - ruby_version: "22-x64"
#    - ruby_version: "21"
#    - ruby_version: "21-x64"
