cache:
- i686-7.1.0-release-win32-dwarf-rt_v5-rev2.7z
- x86_64-7.1.0-release-win32-seh-rt_v5-rev2.7z

install:
  - SET PATH=C:\Ruby%ruby_version%\bin;%PATH%
  - SET RAKEOPT=-rdevkit

  - if not exist "%MINGW_ARCHIVE%" appveyor DownloadFile "%MINGW_URL%" -FileName "%MINGW_ARCHIVE%"
  - 7z x -y "%MINGW_ARCHIVE%" > nul
  - set PATH=%CD%\%MINGW_DIR%\bin;%Path%
  - copy %CD%\%MINGW_DIR%\bin\mingw32-make.exe %CD%\%MINGW_DIR%\bin\make.exe

  - ruby -e "p RUBY_PLATFORM"
  - make --version
  - gcc --version
  - gem --version
  - bundle install
  - make

build: off

test_script:
  - bundle exec rake test
  - gem build fast_excel.gemspec

environment:
  matrix:
    - ruby_version: "24"
      PLATFORM: Win32
      MINGW_DIR: mingw32
      MINGW_URL: https://sourceforge.net/projects/mingw-w64/files/Toolchains%20targetting%20Win32/Personal%20Builds/mingw-builds/7.1.0/threads-win32/dwarf/i686-7.1.0-release-win32-dwarf-rt_v5-rev2.7z/download
      MINGW_ARCHIVE: i686-7.1.0-release-win32-dwarf-rt_v5-rev2.7z
    - ruby_version: "24-x64"
      PLATFORM: x64
      MINGW_DIR: mingw64
      MINGW_URL: https://sourceforge.net/projects/mingw-w64/files/Toolchains%20targetting%20Win64/Personal%20Builds/mingw-builds/7.1.0/threads-win32/seh/x86_64-7.1.0-release-win32-seh-rt_v5-rev2.7z/download
      MINGW_ARCHIVE: x86_64-7.1.0-release-win32-seh-rt_v5-rev2.7z
#    - ruby_version: "23"
#    - ruby_version: "23-x64"
#    - ruby_version: "22"
#    - ruby_version: "22-x64"
#    - ruby_version: "21"
#    - ruby_version: "21-x64"
