cache:
- x86_64-4.9.2-release-win32-seh-rt_v4-rev4.7z
- i686-4.9.2-release-win32-dwarf-rt_v4-rev4.7z

install:
  - SET PATH=C:\Ruby%ruby_version%\bin;%PATH%
  - SET RAKEOPT=-rdevkit

  - if not exist "%MINGW_ARCHIVE%" appveyor DownloadFile "%MINGW_URL%" -FileName "%MINGW_ARCHIVE%"
  - 7z x -y "%MINGW_ARCHIVE%" > nul
  - set Path=%CD%\%MINGW_DIR%\bin;%Path%
  - mingw-get install mingw32-libz

  - make --version
  - gem --version
  - bundle install
  - make
  - mingw-get remove mingw32-libz

build: off

test_script:
  - bundle exec rake test
  - gem build fast_excel.gemspec

environment:
  matrix:
    - ruby_version: "24"
      PLATFORM: Win32
      MINGW_DIR: mingw32
      MINGW_URL: https://sourceforge.net/projects/mingw-w64/files/Toolchains%20targetting%20Win32/Personal%20Builds/mingw-builds/4.9.2/threads-win32/dwarf/i686-4.9.2-release-win32-dwarf-rt_v4-rev4.7z/download
      MINGW_ARCHIVE: i686-4.9.2-release-win32-dwarf-rt_v4-rev4.7z
    - ruby_version: "24-x64"
      PLATFORM: x64
      MINGW_DIR: mingw64
      MINGW_URL: https://sourceforge.net/projects/mingw-w64/files/Toolchains%20targetting%20Win64/Personal%20Builds/mingw-builds/4.9.2/threads-win32/seh/x86_64-4.9.2-release-win32-seh-rt_v4-rev4.7z/download
      MINGW_ARCHIVE: x86_64-4.9.2-release-win32-seh-rt_v4-rev4.7z
#    - ruby_version: "23"
#    - ruby_version: "23-x64"
#    - ruby_version: "22"
#    - ruby_version: "22-x64"
#    - ruby_version: "21"
#    - ruby_version: "21-x64"
