install:
  - SET PATH=C:\Ruby%ruby_version%\bin;%PATH%
  - SET PATH=C:\MinGW\bin;%PATH%
  - SET RAKEOPT=-rdevkit
  - copy c:\MinGW\bin\mingw32-make.exe c:\MinGW\bin\make.exe
  - copy win_deps\zlib.h C:\MinGW\include\zlib.h
  - copy win_deps\zconf.h C:\MinGW\include\zconf.h
  - copy win_deps\x64\zlibwapi.dll z.dll
  - ruby --version
  - gem --version
  - bundle install
  - make

build: off

test_script:
  - bundle exec rake test

environment:
  matrix:
    - ruby_version: "24"
    - ruby_version: "24-x64"
    - ruby_version: "23"
    - ruby_version: "23-x64"
    - ruby_version: "22"
    - ruby_version: "22-x64"
    - ruby_version: "21"
    - ruby_version: "21-x64"
