install:
  - SET PATH=C:\Ruby%ruby_version%\bin;%PATH%
  - SET PATH=C:\MinGW\bin;%PATH%
  - SET RAKEOPT=-rdevkit
  - If Defined ProgramFiles(x86) (copy C:\MinGW\bin\mingw64-make.exe c:\MinGW\bin\make.exe) else (copy C:\MinGW\bin\mingw32-make.exe c:\MinGW\bin\make.exe)
  - If Defined ProgramFiles(x86) (mingw-get install mingw64-libz) else (mingw-get install mingw32-libz)
#  - copy C:\MinGW\bin\mingw32-make.exe c:\MinGW\bin\make.exe
#  - mingw-get install mingw32-libz
  - ruby --version
  - gem --version
  - bundle install
  - make
  - If Defined ProgramFiles(x86) (mingw-get remove mingw64-libz) else (mingw-get remove mingw32-libz)

build: off

test_script:
  - bundle exec rake test
  - gem build fast_excel.gemspec

environment:
  matrix:
    - ruby_version: "24"
    - ruby_version: "24-x64"
#    - ruby_version: "23"
#    - ruby_version: "23-x64"
#    - ruby_version: "22"
#    - ruby_version: "22-x64"
#    - ruby_version: "21"
#    - ruby_version: "21-x64"
